# Generated by Django 5.1.4 on 2025-05-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0007_alter_ball_options_alter_ballinstance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafted_by', to='bd_models.ball')),
            ],
            options={
                'db_table': 'craftingrecipe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CraftingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='craftings.craftingrecipe')),
            ],
            options={
                'db_table': 'craftingingredient',
                'managed': True,
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
